### ISSUE TITLE
API simplification 

### ISSUE THREAD

**Issue by gevgeny** [gcazaciuc/redux-fractal#18]
The API could look shorter and more similar to react-redux.
ie this 

```JavaScript
local({
  key: 'myDumbComp',
  createStore: (props) => {
    return createStore(rootReducer, { filter: true, sort: props.sortOrder })
  }
})(Table);
```
can be replaced with this 

```JavaScript
local({
  createStore: (props) => ({
    myDumbComp: createStore(rootReducer, { filter: true, sort: props.sortOrder }) 
  })
})(Table);
```
or this in case of key based on props
```JavaScript
local({
  createStore: (props) => ({
    [props.tableID]: createStore(rootReducer, { filter: true, sort: props.sortOrder }) 
  })
})(Table);
```

Also `mapStateToProps` and `mapDispatchToProps` are function params in react-redux's `connect`. So it makes sense to leave them (and even `createStore`) as params in `local`

```JavaScript
local(
  (props) => ({ myDumbComp: createStore(rootReducer, { filter: true, sort: props.sortOrder }) }),
  (componentState, ownProps) => ({ filter: getFilter(componentState) }),
  (dispatch) =>({ onFilter: (term) => dispatch(updateSearchTerm(term)) })
)(Table);
```

**Comment by gcazaciuc** [comment]
Regarding the first example:

`key` is a mandatory param for 2 reasons:
1. To enable consist action/state replay which is one of the core values of redux. We could have had a key auto generated but in that case the state would not be serializable/replayable which is one of the core values/advantages you would use redux in the first place(because auto generated ids are not deterministic).
2. To enable local state querying from other parts of the app: eg `state.local[key]`. This includes action creators, selectors, sagas etc.

Regarding mapStateToProps/mapDispatchToProps is debatable and the reasons for having them in current form are:
1. Having them properly labeled makes the intention more clear. No confusion regarding which param is first, which is second.
2. In general it's not a good idea to have anonymous functions, mainly because you loose stack trace and also code clarity, so you would probably have to name the mapStateToProps and mapDispatchToProps functions anyhow.

Given the above i don't see a compelling reason to change the API or introduce breaking changes to it.

**Comment by gevgeny** [comment]
Agree

**Comment by gevgeny** [comment]
Btw, the lib works fine in my app with server-side rendering

**Comment by gcazaciuc** [comment]
Thanks, i'll move it off the todo list then.
