### ISSUE TITLE
Multiple instances of this component?

### ISSUE THREAD

**Issue by brigand** [gcazaciuc/redux-fractal#2]
It wasn't clear to me in the readme if I can render `CompToRender` in multiple places, each with its own state, and how that interacts with the persist flag.

**Comment by gcazaciuc** [comment]
Alright, i'll try to clarify the readme. The answer is yes, every instance of the component has it's own private store. 
So let's assume that you need to render 3 Item components and they are defined like this:
```js
local({
     key: (props) => props.item.id,
     createStore: (props) => {
         return createStore(componentRootReducer, {item: props.item, isEdited: false}); 
   }
})(Item);
```
And somewhere you have
```js
const App = (props) => {
    return(<div>
          <Item item={props.items[0]} />
          <Item item={props.items[0]} />
          <Item item={props.items[0]} />
       </div>
}
ReactDOM.render(<App items={[{id:'a'}, {id:'b'}, {id:'c'}] />, node);
```

If you inspect the app state in redux dev tools you'll notice that there are 3 states created in the global state atom at keys: state.local.a, state.local.b, state.local.c .
When a component dispatches an action only that component store & reducer will catch it and only that component state will update.
When a dispatch on the global store is made by default none of the component stores will catch it. If you want global actions to reach private component stores you need to define the `filterGlobalActions` on the `local` HOC and return true/false from it.
Currently it's not possible to have persist true|false based on the component instance. I'll add very soon the possibility of defining the persist flag as a function of props `persist: (props) => `, so you could tell that you would like Item with id 1 to be persisted but not Item with id 2.

Currently when the persist flag is `true` the components retain their state in the global state atom. Otherwise all state is cleared upon unmounting.
Hope it clears this up

**Comment by gcazaciuc** [comment]
Just pushed 1.2 with the ability to define the persist flag based on component props so now you can decide for each instance whether you want or not to persit it's state upon unmounting. Also added a note in readme about multiple component instances and interaction with the persist flag(check the recipes section).

**Comment by brigand** [comment]
Cool, thanks.
